### ISSUE TITLE
feature request: generate LaTeX source without running pdflatex

### ISSUE THREAD

**Issue by joshuahhh** [uwdata/living-papers#41]
Use cases:
* debugging LaTeX generation
* I have a script that does word-count from LaTeX source; I'd like to run it as I write without spending 10 seconds generating a PDF.

Not super-common use-cases, but it would be nice. More generally, it's interesting to ask whether a living-papers executable should be a one-stop shop (a self-contained build system), or whether it could be more versatile as a UNIX-philosophy "do one thing well" process, to be joined with others in an external build system.

**Comment by jheer** [comment]
This is already supported via the following metadata settings:

```yaml
output:
  latex:
    pdf: false
```
