### ISSUE TITLE
"false positive" DOI not found warnings?

### ISSUE THREAD

**Issue by joshuahhh** [uwdata/living-papers#60]
I've been getting some warnings in terminal output, like:
```
Semantic Scholar: Paper with id DOI:10.1145/2499370.2462170 not found
Semantic Scholar: Paper with id DOI:10.1109/icse.2012.6227133 not found
```
Weird thing is, the PDF is rendering fine, with the aforementioned articles in the bibliography and everything. So I'm not sure what's happening here.

(Haven't tried testing the problem in isolation yet.)

**Comment by jheer** [comment]
This warning means that Semantic Scholar lookup failed, which affects what metadata is then available for tooltips in generated web pages. It does not mean that DOI lookup failed at DOI.org, and so the basic bibliographic record may be fine, it's just not available in Semantic Scholar's index via DOI lookup.
